### ISSUE TITLE
Broken video?

### ISSUE THREAD

**Issue by bamnet** [peterhajas/peterhajas.com#5]
http://peterhajas.com/blog/streamdeck.html includes the following tag:

```html
<p><img src="/media/streamdeck/nav_stack.mp4" alt="Navigation Stacks in my toolkit" /></p>
```

This doesn't render correctly on Chrome 92 running on Windows 10 and whatever the embedded browser in Twitter for Android is.  I see the broken image tofu and the alt text.  Perhaps needs a `<video>` tag or conversion to a GIF.

Nice use of streamdeck!

**Comment by peterhajas** [comment]
(I didn't see this earlier, but 3 years and 2 days late is better than never!)

This has been resolved:

https://peterhajas.com/blog/streamdeck/
